name: Build Component in Native Environment

on:
  push:
    branches: [ main, 'sprint/**', 'release/**', develop ]
  pull_request:
    branches: [ main, 'sprint/**', 'release/**', topic/RDK*, develop ]

env:
  INTERFACES_REF: "2f3d9e2be7b4c8a733375cfe3abc51290130febd"

jobs:
  build-entservices-on-pr:
    name: Build entservices-appmanagers component in github rdkcentral
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rdkcentral/docker-rdk-ci:latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: native build
        run: |
          sh -x build_dependencies.sh
          sh -x cov_build.sh
